import dynamic from "next/dynamic";
import Head from "next/head";
import React from "react";
const Navbar = dynamic(() => import("./Navbar"));
const Footer = dynamic(() => import("./Footer"));

const Layout = ({title, children }) => {
  return (
    <div className="px-20 bg-slate-900 min-h-[100vh]">
      <Head>
        <title>{title ? title + ' | AviCart' : 'AviCart'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keword" content="AviCart next app Ecommerce" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div>
        <header>
          <Navbar />
        </header>
        <main className="min-h-[100vh] text-white">{children}</main>
        <footer>
          <Footer />
        </footer>
      </div>
    </div>
  );
};

export default Layout;
