const data = {
    products: [
        {
            name: 'Free Shirt',
            slug: 'free-shirt',
            category: 'Shirts',
            image: '/images/shirt1.jpeg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Fit Shirt',
            slug: 'fit-shirt',
            category: 'Shirts',
            image: '/images/shirt2.jpeg',
            price: 70,
            brand: 'Adidas',
            rating: 3.2,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Slim Shirt',
            slug: 'slim-shirt',
            category: 'Shirts',
            image: '/images/shirt3.jpg',
            price: 80,
            brand: 'Raymond',
            rating: 4.5,
            numReviews: 3,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Golf Pant',
            slug: 'golf-pant',
            category: 'Pants',
            image: '/images/pant1.jpeg',
            price: 90,
            brand: 'Oliver',
            rating: 2.9,
            numReviews: 13,
            countInStock: 20,
            description: 'Smart looking pant',
        },
        {
            name: 'Fit Pant',
            slug: 'fit-pant',
            category: 'Pants',
            image: '/images/pant2.jpg',
            price: 95,
            brand: 'Oliver',
            rating: 3.9,
            numReviews: 7,
            countInStock: 20,
            description: 'Smart looking pant',
        },
        {
            name: 'Classic Pant',
            slug: 'classic-pant',
            category: 'Pants',
            image: '/images/pant3.jpg',
            price: 95,
            brand: 'Monte Carlo',
            rating: 4.9,
            numReviews: 6,
            countInStock: 20,
            description: 'Smart looking pant',
        },

    ]
}

export default data